admin_password: admin
registry:
  count: 1
  cpus: 1
  memory: 1000
master:
  count: 1
  cpus: 2
  memory: 1800
  mode: cluster
worker:
  count: 2
  cpus: 2
  memory: 4500
ip:
  registryServer: 192.168.120.90
  nfsServer: 192.168.120.91
  master: 192.168.120.100
  worker:   192.168.120.110
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
