admin_password: admin
master:
  count: 1
  cpus: 2
  memory: 1800
worker:
  count: 1
  cpus: 2
  memory: 1800
ip:
  server: 192.168.120.90
  master: 192.168.120.100
  worker:   192.168.120.110
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
